apiVersion: v1
kind: Service
metadata:
  name: amiyabot-minigame-center-website-service
  namespace: amiya-bot
spec:
  selector:
    app: amiyabot-minigame-center-website
  ports:
  - name: port-80
    protocol: TCP
    port: 80
    targetPort: 80